@startuml
Participant User
Participant Client
Participant Server
Participant Database
title Allocate Employee Sequence Diagram

User->Client: Requests to enter edit view 
Client->User: Displays edit view for the user

User->Client: Drags and drops an employee onto a job
Client->>Server: Sends request to allocate employee to job

activate Server
alt Success
    Server->Database: Update employee allocation for the job
    Database-->>Server: Confirmation of allocation update

    Server-->>Client: Sends confirmation of allocation update
else Failure
    Server-->>Client: Sends error message
end
deactivate Server

Client->User: Displays the allocated employee on the job
@enduml