Participant User
Participant Client 
Participant Server
Participant Database
title Archive Job

User->Client: Requests to enter edit view 
Client->User: Displays edit view for the user

User->Client: Clicks on Archive button 
Client->>Server: Sends request to archive the job
    activate Server

alt Success
    Server->Database: Change job to the archive category
    Server->Database: Release all employees working on the job
    Database-->>Server: Confirmation of archive

    Server-->>Client: Sends confirmation of job archiving and employee release
else failure
    Server-->>Client: Sends failure notification
end
    deactivate Server

Client->User: Displays job in archived section or displays error message