@startuml
Participant Admin
Participant Client
Participant Server
Participant Database
title Change User Password Sequence Diagram

Admin->Client: Click on change user password button
Client->Admin: Displays change password form for the admin
Admin->Client: Enters new password for user
Client->>Server: Sends request to change user password

activate Server
alt Success
    Server->Database: Validates admin's authorization
    Database-->>Server: Authorization success


        Server->Database: Validates user existence and authorization
        Database-->>Server: User validation success
        Server->Database: Changes user password
        Database-->>Server: Password change success

        Server-->>Client: Sends password change confirmation

else Failure
    Server-->>Client: Sends failure notification
end
deactivate Server

Client->Admin: Displays password change success or failure message
@enduml