@startuml
Participant Admin
Participant Client
Participant Server
Participant Database

title Account Creation/Validation Sequence Diagram

Admin->Client: Requests to create an account
Client->Admin: Displays account creation form

Admin->Client: Enters account details
Client->>Server: Sends request to create an account

activate Server
alt Success

        Server->Database: Creates a new account
        Database-->>Server: Account creation success

else Failure (same username)
    Server-->>Client: Sends failure notification
end
deactivate Server

Client->Admin: Displays account creation success or failure message
@enduml