Participant User
Participant Client
Participant Server
Participant Database
title Edit Employee Detail Sequence Diagram

User->Client: Requests to enter edit view

Client->User: Displays edit view for the user

User->Client: Updates the employee detail
Client->>Server: Sends request to update employee detail

alt Success

activate Server
Server->Database: Update employee detail  in the database
Database-->>Server: Confirmation of update

Server-->>Client: Sends confirmation of update

else Failure 
Server-->>Client: Sends error message

end
deactivate Server

Client->User: Displays updated employee detail or error message