@startuml
Participant User
Participant Client 
Participant Server
Participant Database
title Edit Job Detail

User->Client: Requests to enter edit view 
Client->User: Displays edit view for the user
User->Client: Modifies the information of the job
Client->>Server: Sends request to update job information

alt Success
    activate Server
    Server->Database: Update job information in the database
    Database-->>Server: Confirmation of update

    Server-->>Client: Sends confirmation of update
else failure
    Server-->>Client: Sends error message
end
    deactivate Server

Client->User: Displays the updated job/ view error message
@enduml