@startuml
Participant Admin
Participant Client
Participant Server
Participant Database
title Load Data Backup Sequence Diagram

Admin->Client: Requests to load data backup
Client->Admin: Displays data backup loading form for the admin

Admin->Client: Selects the backup file to load
Client->>Server: Sends request to load data backup

activate Server
alt Data Backup Loading Success
    Server->Database: Loads the data backup from the selected file
    Database-->>Server: Data backup loading success

    Server-->>Client: Sends data backup loading confirmation
else Data Backup Loading Failure
    Server-->>Client: Sends data backup loading failure notification
end
deactivate Server

Client->Admin: Displays the data backup loading success message
@enduml