@startuml

skin rose

title  Login Sequence Diagram
actor User
participant Client
participant Server
participant Database as DB

activate User
User -> Client : enter username & password
Activate Client
User -> Client : log me in pls
Client -> Client : pre-validate username & password

alt username/password good
    Client -[#blue]>> Server : login details
    activate Server

    opt #RosyBrown server timeout (>5secs)
    User <- Client : server not responding
    end

    Server -> Server : sanitize inputs
    Server -> DB : SELECT password WHERE username
    
    alt password returned
        activate DB
        Server <-- DB : encrypted password
        Server -> Server : Decrypt password
        Server -> Server : do passwords match?
        alt succesful login
            Client <<-[#blue]- Server : login successful
            User <- Client : login successful
        else #pink incorrect password
            Client <<-[#blue]- Server : username/password dont match
            User <- Client : username/password dont match
        end
    else #pink no results returned (account doesn't exist)
        Server <-- DB : no results
        deactivate DB
        Client <<-[#blue]- Server : username/password dont match
        User <- Client : username/password dont match
    else #RosyBrown timeout, >5secs (DB can't respond)
        Client <-[#blue]- Server : database can't respond
        deactivate Server
        User <- Client : database can't respond\nsomething went wrong
    end

else #pink username/password empty
    User <- Client : username/password must be filled
else #pink too many tries (15 tries)
    Client -> Client : lock system for 10 mins
    User <- Client : Too many tries, try again later
    deactivate Client
end

@enduml