@startuml
Participant User
Participant Client
Participant Server

title View Documentation

User->Client: Clicks "Documentation" tab
Client->User: Displays the documentation page

Client->Server: Request documentation page content
Server->Client: Returns HTML to client
@enduml