@startuml
Participant Admin
Participant Client
Participant Server
Participant Database
title View Diagnostic Data Sequence Diagram

Admin->Client: Requests to view diagnostic data

Client->>Server: Sends request to retrieve diagnostic data

activate Server
alt  Success
    Server->Database: Retrieve diagnostic data
    Database-->>Server: Return data

else Failure
    Server-->>Client: Sends returned data
end
deactivate Server

Client->Admin: Displays the retrieved diagnostic data or failure message
@enduml