@startuml

skin rose
left to right direction

actor "Construction Manager" AS ConMan
actor "Admin" AS admin

rectangle "System Boundary\n\nAnything with a blue border is not really a use case as they are already done/visible on connected use case" #text:blue {
    'Manager stuff
    ConMan -- (Login)

    (View Manager Navbar) AS VMN #line:blue;
    (Login) <.. VMN : <<includes>>


    (View Job Page) AS VJP
    (View Employee Page) AS VEP
    (View Account Page) AS VAP
    (View History Page)

    (View Employee Details) AS VED
    (View Job Details) AS VJD

    'manager navbar
    VMN <.. VJP : <<extend>>
    VMN <.. VEP : <<extend>>
    VMN <.. VAP : <<extend>>
    VMN <.. (View History Page) : <<extend>>
    VMN <.. (Logout) : <<extend>>
    VMN <.. (View Help Page) : <<extend>>

    'employee page
    VEP <.. (Pin Employee[s]) : <<extend>>
    (Pin Employee[s]) <.. (Unpin Employee[s]) : <<extend>>
    (Pin Employee[s]) <.. (Batch Add To Job) : <<extend>>
    VEP <.. (Add New Employee) : <<extend>>
    (Add New Employee) <.. (Upload Employee Image) : <<extend>>
    VEP <.. (Show Archived Employees) : <<extend>>
    (Show Archived Employees) <.. (Archive Employee) : <<extend>>
    (Show Archived Employees) <.. (Unarchive Employee) : <<extend>>
    VEP <.. (Change Active Status\n[Active/Inactive/School]) : <<extend>>
    VEP <.. (Sort/Filter/Search Employees) : <<extend>>
    (Auto Refresh) #line:blue;
    VEP <.. (Auto Refresh) : <<extend>>

    VEP <.. VED : <<extend>>
    'employee details screen
    VED <.. (Upload Employee Image) : <<extend>>
    VED <.. (Edit Employee Details) : <<extend>>
    (View Where Last Assigned) #line:blue;
    VED <.. (View Where Last Assigned) : <<extend>>
    (Edit Employee Details) <.. (Delete Employee) : <<extend>>
    (Edit Employee Details) <.. (Archive Employee) : <<extend>>
    (Edit Employee Details) <.. (Unarchive Employee) : <<extend>>
    (Edit Employee Details) <.. (Change Active Status\n[Active/Inactive/School]) : <<extend>>


    'job page
    VJP <.. (VED) : <<extend>>
    VJP <.. (Auto Refresh) : <<extend>>
    VJP <.. (Sort/Filter/Search Jobs) : <<extend>>
    VJP <.. (Custom Sort Jobs\n[+ upload to projector]) : <<extend>>
    VJP <.. (Allocate/Move Employee) : <<extend>>
    VJP <.. (Add New Job) : <<extend>>
    VJP <.. (Edit Outlook) : <<extend>>
    VJP <.. (View Projector View) : <<extend>>
    (View Employee Totals) #line:blue;
    VJP <.. (View Employee Totals) : <<extend>>
    VJP <.. (Change Active Status\n[Active/Inactive/School]) : <<extend>>

    'view employee list on job page
    (View Employee List) AS VEL #line:blue;
    VJP <.. VEL : <<extend>>
    VEL <.. (Show All Employees) : <<extend>>
    (Allocate/Move Employee) ..> (Show All Employees)  : <<extend>>\n[ALLOWS DUPLICATES]
    VEL <.. (Show Unassigned Employees) : <<extend>>
    (Allocate/Move Employee) ..> (Show Unassigned Employees) : <<extend>>
    (Allocate/Move Employee) <.. (Duplicate Employee) : <<extend>>


    VJP <.. (VJD) : <<extend>>
    'job details screen
    VJD <.. (Edit Job Details) : <<extend>>
    (Edit Job Details) <.. (Unarchive Job) : <<extend>>
    (Edit Job Details) <.. (Archive Job) : <<extend>>
    (Edit Job Details) <.. (Delete Job) : <<extend>>
    'VJD <.. (Edit Outlook) : <<extend>> it was in figma, no longer doing this, putting graph there instead
    (View Projected vs Actual\n Employee Count Graph) AS viewgraphs  #line:blue;
    VJD <.. viewgraphs : <<extend>>

    'account page
    (Change Password\n[Forced for new accounts\nor had password reset]) AS changepass
    VAP <.. changepass : <<extend>>
    VAP <.. (Change Background Image) : <<extend>>
    VAP <.. (Change Username) : <<extend>>
    VAP <.. (Set/Disable Refresh Interval) : <<extend>>

    'history page
    (View Projected vs Actual \nEmp Count for Archived Jobs) #line:blue;
    (View History Page) <.. (View Projected vs Actual \nEmp Count for Archived Jobs) : <<extend>>
    (View History Page) <.. (Show All Jobs) : <<extend>>
    (View History Page) <.. (Adjust Range) : <<extend>>
    (View History Page) <.. (Next/Previous Page) : <<extend>>
    (View History Page) <.. (Change Jobs Per Page) : <<extend>>
    (View History Page) <.. (VJD) : <<extend>>

    ' Admin Stuff
    admin -- (Admin Login)
    (View Admin Navbar) AS VAN #line:blue;
    (Admin Login) <.. VAN : <<includes>>
    VAN <.> (VMN) : <<extend>>\n(only if admin)
    VAN <.. (View Documentation) : <<extend>>
    (View Admin Functions) AS VAF
    VAN <.. VAF : <<extend>>
    VAF <.. (Create Manager Account) : <<extend>>
    VAF <.. (Reset User's Password) : <<extend>>
    VAF <.. (Load Database Backup) : <<extend>>
    VAF <.. (Download Database Backup) : <<extend>>
    VAF <.. (Upload Database Backup) : <<extend>>
    VAF <.. (Upload Employee CSV) : <<extend>>
    VAF <.. (Upload Job CSV) : <<extend>>

    changepass .up. (Reset User's Password) #gray
    changepass .up. (Create Manager Account) #gray

}
@enduml