@startuml

skin rose

title Add Employee

Actor User
Participant Client 
Participant Server
Database Database AS DB

User -> Client: Clicks 'Add Employee'
Client -> User: Displays Add Employee Form
User -> Client: Completes and Submits form
Client ->> Client: Validates input
alt Validated (Client Side)
activate Server
Client -> Server: Sends Information to add-employee.php
Server -> Server: Validate data and Image
alt Validated (Server Side)
Server -> DB: Inserts new employee into database
Server -> Client: New Employee ID
Client -> User: Display new employee's page
else Failure
Server -> Client: Failure message
Client -> User : Display Server validation error
end
deactivate Server
else Failure
Client -> User: Displays failed validation
end
@enduml