@startuml

skin rose

title Add Job Sequence Diagram

Actor User
Participant Client 
Participant Server
Database Database AS DB

User->Client: Add new job button
User <- Client: Makes Add Job Form visible

loop every field user wants to fill
    User -> Client: Fill out field
    Client -> Client: Validates input
    Client -> User: Displays if fields are valid
end

opt user clicks cancel
    User -> Client: Clicks cancel
    Client -> Client : Clears form \n+ validation styles
    User <- Client: Hides form 
end

opt user clicks off overlay
    User -> Client: Clicks off overlay
    User <- Client: Hides form 
end

User -> Client: Clicks submit
Client -> Client: Validates input

Client ->> Server: addJob.php with fields
Server -> Server: Validates input

Server->DB: INSERT new job
return new job's id

Client <--Server: new job's id
Client -> Client: jobDetails(id)\n(see usecase for job details)

Client->User: Displays new job's details

@enduml