@startuml
skin rose

title Change Employee Status

Actor User
Participant Client 
Participant Server
Database Database AS DB

User->Client: Drags Employee to different status section
alt Edit Employee
User -> Client: Saves an employee edit with a new status
end
alt Selected Inactive or School from Active
Client -> Server: Request current employee assignments
Server<->DB:Select list of assignments
Server->Client: If assignments exist, send list
Client->Client: Format list as warning overlay
Client->User: Display overlay
break Cancel
User->Client: Cancel changes
Client->Client: Reset changes
end
alt Continue
User->Client: Continue with removal
Client->Server: Request employee to be removed from jobs
Server<->DB: Remove employee from all jobs
end 
end
Client->Server: Send new status and employee ID
Server<->DB: Update employee's active column
Server->Client:Success/Failure
Client->User: Update Employee's location/active status card
@enduml