@startuml

skin rose

title Edit Employee

Actor User
Participant Client 
Participant Server
Database Database AS DB

User -> Client: Clicks Edit employee button
Client -> User: Replaces text elements with input elements
User -> Client: Completes and Submits form
Client ->> Client: Validates input
alt Validated (Client Side)
activate Server
Client -> Server: Sends Information to update-employee.php
Server -> Server: Validate data and Image
alt Validated (Server Side)
Server -> DB: Updates employee in database
Server -> Client: Success/Failure
Client -> User: Display Result
else Failure
Server -> Client: Failure message
Client -> User : Display Server validation error
end
deactivate Server
else Failure
Client -> User: Displays failed validation
end
@enduml