@startuml
skin rose
skinparam participantPadding 20
skinparam participantBorderColor black

title Import CSV Sequence Diagram

actor User
participant Client
participant Server
participant Database

User -> Client: Selects CSV file for import
Client -> Client: Validates user
Client -> Client: Validates file format (CSV)
Client --> User: Displays results in a html form
User -> Client: Makes edits and confirms import
Client -> Server: Request: Import CSV
Server -> Database: Insert data from CSV
Server -> Client: Import success message
Client --> User: Displays success message

@enduml