@startuml
skin rose
skinparam participantPadding 20
skinparam participantBorderColor black

title load Backup Sequence Diagram

actor User
participant Client
participant Server
participant Database

User -> Client: Selects .sql file to load
Client -> Client: Validates user as admin
Client -> Client: Validates file format
Client --> User: Displays warning message
User -> Client: Confirms load backup
Client -> Server: Request: Upload Backup by calling loadBackup.php
Server -> Database: Execute mysql command
Database -> Database: Update backup data
Server -> Client: Redirect to Jobs Page
Client --> User: Redirected to Jobs Page

@enduml