@startuml

skin rose

title View Employee

Actor User
Participant Client 
Participant Server
Database Database AS DB

User -> Client: Clicks on an Employee Card
Client -> Server: Requests selected employee data
Server -> DB: Querys for specific employee info
DB -> Server: Returns Employee row
Server -> Client: Returns employee Data formatted as HTML
Client -> User: Displays employee data in overlay

@enduml